server:
  port: 8080
spring:
  application:
    name: heatmap
  datasource:
    url: jdbc:h2:mem:heatmap;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded
  security:
    user:
      name: ${HEATMAP_USER:admin}
      password: ${HEATMAP_PASS:secret}
