server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
spring:
  application:
    name: heatmap
  datasource:
    url: jdbc:h2:mem:heatmap;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded
  security:
    user:
      name: ${HEATMAP_USER:admin}
      password: ${HEATMAP_PASS:admin}
  mvc:
    throw-exception-if-no-handler-found: true
